apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nightshift-data
  namespace: nightshift
  labels:
    app: nightshift
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
